"""Guardrail against the same bug class as "работник" (report-34/35): a
short, bare, generic single-word entry in one of settings.yaml's topic
term lists (anything ending in "_terms" holding a plain list of strings)
will eventually fire in a context that has nothing to do with the list's
intent. Confirmed real case: `employment_context_terms` contained bare
"работник"/"працаўнік", which gave a silent +14 category-weight boost to
"Работа, зарплаты и доходы" for any story mentioning any kind of worker
("работники МЧС", "медицинские работники"...) -- confirmed via a fire-
rescue story that got miscategorized with an empty subcategory (the tell
that the weight came from a bonus channel, not a genuine keyword hit).

Unlike the EVENT_OBJECT/PROBLEM regex lint (test_lint_bare_object_problem_
patterns.py), `term_present()` already anchors single-word terms to word
boundaries (see social_monitor.py), so the risk here is NOT substring
collision -- it's pure semantic over-breadth: a correctly-spelled,
correctly-anchored generic word (турист, работник, дом...) that's simply
too common to reliably signal what the list intends.

IMPORTANT HONESTY NOTE: unlike the EVENT_OBJECT/PROBLEM baseline (every
entry there was individually reasoned through for plausible false-friend
collisions), this baseline of ~420 entries is a MECHANICAL freeze, not a
claim that each one has been semantically vetted. A first pass flagged one
concrete residual risk worth tracking:

  - `tourism_exclusion_terms` contains bare "турист"/"путешествен". This
    list drives an EXCLUSION (not just a category label), gated by
    `resident_explicit_signal or finding_hits or persistence_hits or
    domestic_consumer_hits` -- so it is NOT as exposed as the ungated
    `employment_context_terms` was. But the override requires a "resident"
    term (жители/местные/...) co-occurring with a complaint term in the
    same detail; a complaint narrated through tourists themselves (e.g.
    "туристы жалуются на грязные пляжи Беларуси") may not trip that
    specific override. No confirmed real leak found for this one -- it's
    flagged as a residual risk to watch, not fixed pre-emptively without
    evidence, consistent with how every other fix in this project was
    made only after a real production example confirmed it.

As with the other lint, this test freezes what exists today so a NEW bare
entry added to any `*_terms` list is caught at review time. Extending an
existing list with a new bare short entry, or adding a new `*_terms` list
containing one, will fail this test until the entry is either phrased as a
multi-word phrase (the existing convention throughout settings.yaml -- see
e.g. "дефицит бюджета" instead of bare "дефицит") or deliberately added to
REVIEWED_BASELINE below with a comment.
"""

from pathlib import Path

import yaml


SETTINGS_PATH = Path(__file__).resolve().parents[1] / "config" / "settings.yaml"


def _scan_bare_short_terms(max_len: int = 12) -> set[tuple[str, str]]:
    data = yaml.safe_load(SETTINGS_PATH.read_text(encoding="utf-8"))
    topic = data["topic"]
    found = set()
    for key, value in topic.items():
        if not key.endswith("_terms") or not isinstance(value, list):
            continue
        for term in value:
            if not isinstance(term, str):
                continue
            if term.startswith("re:"):
                continue
            if " " not in term.strip() and len(term) <= max_len:
                found.add((key, term))
    return found


# Mechanical freeze as of update75 (2026-09-03) -- see the honesty note
# above. Generated from the live file, not hand-typed, to avoid
# transcription errors.
REVIEWED_BASELINE: set[tuple[str, str]] = {
    ('belarus_context_terms', 'бабруйск'),
    ('belarus_context_terms', 'баранович'),
    ('belarus_context_terms', 'барысаў'),
    ('belarus_context_terms', 'беларус'),
    ('belarus_context_terms', 'белорус'),
    ('belarus_context_terms', 'бобруйск'),
    ('belarus_context_terms', 'борисов'),
    ('belarus_context_terms', 'брест'),
    ('belarus_context_terms', 'брэст'),
    ('belarus_context_terms', 'витеб'),
    ('belarus_context_terms', 'вобласць'),
    ('belarus_context_terms', 'віцеб'),
    ('belarus_context_terms', 'гомел'),
    ('belarus_context_terms', 'гомель'),
    ('belarus_context_terms', 'гродна'),
    ('belarus_context_terms', 'гродно'),
    ('belarus_context_terms', 'дзержинск'),
    ('belarus_context_terms', 'дзяржынск'),
    ('belarus_context_terms', 'жодзіна'),
    ('belarus_context_terms', 'жодин'),
    ('belarus_context_terms', 'магіл'),
    ('belarus_context_terms', 'маладзечна'),
    ('belarus_context_terms', 'минск'),
    ('belarus_context_terms', 'могил'),
    ('belarus_context_terms', 'молодечно'),
    ('belarus_context_terms', 'мінск'),
    ('belarus_context_terms', 'область'),
    ('belarus_context_terms', 'орш'),
    ('belarus_context_terms', 'пинск'),
    ('belarus_context_terms', 'пінск'),
    ('belarus_context_terms', 'райвыканкам'),
    ('belarus_context_terms', 'райисполком'),
    ('belarus_context_terms', 'салігорск'),
    ('belarus_context_terms', 'слуцк'),
    ('belarus_context_terms', 'смолевич'),
    ('belarus_context_terms', 'солигорск'),
    ('belarus_regulatory_context_terms', 'саўмін'),
    ('belarus_regulatory_context_terms', 'совмин'),
    ('building_envelope_context_terms', 'капремонт'),
    ('building_envelope_context_terms', 'многоэтажк'),
    ('building_envelope_context_terms', 'подъезд'),
    ('building_envelope_context_terms', 'тынкоўк'),
    ('building_envelope_context_terms', 'фасад'),
    ('building_envelope_context_terms', 'штукатурк'),
    ('building_envelope_problem_terms', 'абсыпаецца'),
    ('building_envelope_problem_terms', 'адвальваецца'),
    ('building_envelope_problem_terms', 'осыпается'),
    ('building_envelope_problem_terms', 'осыпалась'),
    ('building_envelope_problem_terms', 'осыпание'),
    ('building_envelope_problem_terms', 'отваливается'),
    ('building_envelope_problem_terms', 'отвалилась'),
    ('construction_problem_exception_terms', 'аварийн'),
    ('construction_problem_exception_terms', 'возмущ'),
    ('construction_problem_exception_terms', 'дефект'),
    ('construction_problem_exception_terms', 'долгострой'),
    ('construction_problem_exception_terms', 'жалоб'),
    ('construction_problem_exception_terms', 'задерж'),
    ('construction_problem_exception_terms', 'небяспечн'),
    ('construction_problem_exception_terms', 'некачествен'),
    ('construction_problem_exception_terms', 'опасн'),
    ('construction_problem_exception_terms', 'отставан'),
    ('construction_problem_exception_terms', 'скарг'),
    ('construction_problem_exception_terms', 'трещин'),
    ('domestic_consumer_context_terms', 'крама'),
    ('domestic_consumer_context_terms', 'магазин'),
    ('domestic_consumer_context_terms', 'пакупнік'),
    ('domestic_consumer_context_terms', 'покупател'),
    ('domestic_consumer_context_terms', 'потребител'),
    ('domestic_consumer_context_terms', 'продаж'),
    ('domestic_consumer_context_terms', 'реализац'),
    ('domestic_consumer_context_terms', 'спажывец'),
    ('domestic_regulatory_discussion_terms', 'закон'),
    ('domestic_regulatory_discussion_terms', 'законапраект'),
    ('domestic_regulatory_discussion_terms', 'законопроект'),
    ('domestic_regulatory_discussion_terms', 'запрет'),
    ('domestic_regulatory_discussion_terms', 'кодекс'),
    ('domestic_regulatory_discussion_terms', 'пастанова'),
    ('domestic_regulatory_discussion_terms', 'правила'),
    ('domestic_regulatory_discussion_terms', 'правілы'),
    ('domestic_regulatory_discussion_terms', 'требования'),
    ('domestic_regulatory_discussion_terms', 'штраф'),
    ('emergency_event_terms', 'бура'),
    ('emergency_event_terms', 'буря'),
    ('emergency_event_terms', 'галалёд'),
    ('emergency_event_terms', 'галолед'),
    ('emergency_event_terms', 'гроз'),
    ('emergency_event_terms', 'завірух'),
    ('emergency_event_terms', 'залева'),
    ('emergency_event_terms', 'ливен'),
    ('emergency_event_terms', 'ливн'),
    ('emergency_event_terms', 'метель'),
    ('emergency_event_terms', 'навальніц'),
    ('emergency_event_terms', 'наводнен'),
    ('emergency_event_terms', 'непогод'),
    ('emergency_event_terms', 'паводк'),
    ('emergency_event_terms', 'паводок'),
    ('emergency_event_terms', 'снегопад'),
    ('emergency_event_terms', 'стих'),
    ('emergency_event_terms', 'стых'),
    ('emergency_event_terms', 'ураган'),
    ('emergency_event_terms', 'шквал'),
    ('employment_context_terms', 'неоплачиваем'),
    ('employment_context_terms', 'працадаўц'),
    ('employment_context_terms', 'работодатель'),
    ('employment_context_terms', 'стажиров'),
    ('employment_context_terms', 'стажыроў'),
    ('employment_context_terms', 'трудоустрой'),
    ('explicit_complaint_terms', 'абур'),
    ('explicit_complaint_terms', 'возмущ'),
    ('explicit_complaint_terms', 'жалова'),
    ('explicit_complaint_terms', 'жалу'),
    ('explicit_complaint_terms', 'навяза'),
    ('explicit_complaint_terms', 'навязан'),
    ('explicit_complaint_terms', 'нарекан'),
    ('explicit_complaint_terms', 'недоволь'),
    ('explicit_complaint_terms', 'незадавол'),
    ('explicit_complaint_terms', 'паскардз'),
    ('explicit_complaint_terms', 'пожаловал'),
    ('explicit_complaint_terms', 'претензи'),
    ('explicit_complaint_terms', 'прэтэнзі'),
    ('explicit_complaint_terms', 'скардз'),
    ('explicit_complaint_terms', 'смутил'),
    ('financial_forecast_exclusion_terms', 'биткоин'),
    ('financial_forecast_exclusion_terms', 'криптовалют'),
    ('financial_forecast_exclusion_terms', 'фрс'),
    ('forecast_exclusion_terms', 'ожидается'),
    ('forecast_exclusion_terms', 'прагназуецца'),
    ('forecast_exclusion_terms', 'синоптик'),
    ('forecast_exclusion_terms', 'сіноптык'),
    ('forecast_exclusion_terms', 'чакаецца'),
    ('foreign_context_terms', 'american'),
    ('foreign_context_terms', 'danube'),
    ('foreign_context_terms', 'америка'),
    ('foreign_context_terms', 'амерыка'),
    ('foreign_context_terms', 'англи'),
    ('foreign_context_terms', 'бишкек'),
    ('foreign_context_terms', 'ближневост'),
    ('foreign_context_terms', 'блізкаўсход'),
    ('foreign_context_terms', 'британ'),
    ('foreign_context_terms', 'варшав'),
    ('foreign_context_terms', 'великобрит'),
    ('foreign_context_terms', 'вильнюс'),
    ('foreign_context_terms', 'вільнюс'),
    ('foreign_context_terms', 'герман'),
    ('foreign_context_terms', 'германі'),
    ('foreign_context_terms', 'грузи'),
    ('foreign_context_terms', 'грузі'),
    ('foreign_context_terms', 'днестр'),
    ('foreign_context_terms', 'днястр'),
    ('foreign_context_terms', 'дунай'),
    ('foreign_context_terms', 'душанбе'),
    ('foreign_context_terms', 'европ'),
    ('foreign_context_terms', 'еўроп'),
    ('foreign_context_terms', 'итал'),
    ('foreign_context_terms', 'калифорн'),
    ('foreign_context_terms', 'каліфорн'),
    ('foreign_context_terms', 'каракуль'),
    ('foreign_context_terms', 'киев'),
    ('foreign_context_terms', 'киргиз'),
    ('foreign_context_terms', 'китай'),
    ('foreign_context_terms', 'київ'),
    ('foreign_context_terms', 'кыргыз'),
    ('foreign_context_terms', 'кіеў'),
    ('foreign_context_terms', 'кітай'),
    ('foreign_context_terms', 'латвий'),
    ('foreign_context_terms', 'латвій'),
    ('foreign_context_terms', 'литов'),
    ('foreign_context_terms', 'лос-анджелес'),
    ('foreign_context_terms', 'лос-анджэлес'),
    ('foreign_context_terms', 'літов'),
    ('foreign_context_terms', 'молдов'),
    ('foreign_context_terms', 'москв'),
    ('foreign_context_terms', 'нарв'),
    ('foreign_context_terms', 'нефтян'),
    ('foreign_context_terms', 'ориндж'),
    ('foreign_context_terms', 'орындж'),
    ('foreign_context_terms', 'памир'),
    ('foreign_context_terms', 'польск'),
    ('foreign_context_terms', 'польшч'),
    ('foreign_context_terms', 'расі'),
    ('foreign_context_terms', 'росси'),
    ('foreign_context_terms', 'саудаў'),
    ('foreign_context_terms', 'саудов'),
    ('foreign_context_terms', 'славакі'),
    ('foreign_context_terms', 'славац'),
    ('foreign_context_terms', 'словаки'),
    ('foreign_context_terms', 'словац'),
    ('foreign_context_terms', 'сша'),
    ('foreign_context_terms', 'таджик'),
    ('foreign_context_terms', 'тбилис'),
    ('foreign_context_terms', 'тбіліс'),
    ('foreign_context_terms', 'токтогуль'),
    ('foreign_context_terms', 'украин'),
    ('foreign_context_terms', 'украін'),
    ('foreign_context_terms', 'уэльс'),
    ('foreign_context_terms', 'фудзи'),
    ('foreign_context_terms', 'шотланд'),
    ('foreign_context_terms', 'эстон'),
    ('foreign_context_terms', 'эстоні'),
    ('foreign_context_terms', 'япон'),
    ('foreign_context_terms', 'італ'),
    ('hotel_service_context_terms', 'гасцініц'),
    ('hotel_service_context_terms', 'гостиниц'),
    ('hotel_service_context_terms', 'отел'),
    ('hotel_service_context_terms', 'постоялец'),
    ('housing_context_terms', 'дом'),
    ('housing_context_terms', 'дома'),
    ('housing_context_terms', 'доме'),
    ('housing_context_terms', 'жиль'),
    ('housing_context_terms', 'жылл'),
    ('housing_context_terms', 'имущество'),
    ('housing_context_terms', 'квартир'),
    ('housing_context_terms', 'кватэр'),
    ('housing_context_terms', 'комнат'),
    ('housing_context_terms', 'маёмасц'),
    ('housing_context_terms', 'общежити'),
    ('housing_context_terms', "пад'езд"),
    ('housing_context_terms', 'пакой'),
    ('housing_context_terms', 'подъезд'),
    ('housing_context_terms', 'стены'),
    ('housing_context_terms', 'сцены'),
    ('housing_context_terms', 'інтэрнат'),
    ('housing_problem_terms', 'влажн'),
    ('housing_problem_terms', 'вільгот'),
    ('housing_problem_terms', 'затоп'),
    ('housing_problem_terms', 'плесен'),
    ('housing_problem_terms', 'плесень'),
    ('housing_problem_terms', 'протеч'),
    ('housing_problem_terms', 'сырасц'),
    ('housing_problem_terms', 'сырост'),
    ('housing_problem_terms', 'цвіль'),
    ('illegal_recruitment_terms', 'наемник'),
    ('illegal_recruitment_terms', 'наемничество'),
    ('illegal_recruitment_terms', 'найміт'),
    ('illegal_recruitment_terms', 'найміцтва'),
    ('illegal_recruitment_terms', 'наёмник'),
    ('illegal_recruitment_terms', 'наёмничество'),
    ('institutional_finding_terms', 'завышен'),
    ('institutional_finding_terms', 'оштрафован'),
    ('institutional_finding_terms', 'просрочен'),
    ('macroeconomic_exclusion_terms', 'ввп'),
    ('macroeconomic_exclusion_terms', 'врп'),
    ('macroeconomic_exclusion_terms', 'макроэконом'),
    ('natural_water_environment_problem_terms', 'высыхает'),
    ('natural_water_environment_problem_terms', 'забрудж'),
    ('natural_water_environment_problem_terms', 'загрязнен'),
    ('natural_water_environment_problem_terms', 'нафтапрадукт'),
    ('natural_water_environment_problem_terms', 'нефтепродукт'),
    ('natural_water_environment_problem_terms', 'нечистот'),
    ('natural_water_environment_problem_terms', 'обмел'),
    ('natural_water_environment_problem_terms', 'сцёкав'),
    ('natural_waterbody_context_terms', 'вадасховішч'),
    ('natural_waterbody_context_terms', 'вадаём'),
    ('natural_waterbody_context_terms', 'водоем'),
    ('natural_waterbody_context_terms', 'водохранилищ'),
    ('natural_waterbody_context_terms', 'водоём'),
    ('natural_waterbody_context_terms', 'возера'),
    ('natural_waterbody_context_terms', 'озеро'),
    ('natural_waterbody_context_terms', 'пруд'),
    ('natural_waterbody_context_terms', 'рака'),
    ('natural_waterbody_context_terms', 'река'),
    ('natural_waterbody_context_terms', 'ручей'),
    ('natural_waterbody_context_terms', 'сажалк'),
    ('natural_waterbody_problem_terms', 'абмял'),
    ('natural_waterbody_problem_terms', 'вадаём'),
    ('natural_waterbody_problem_terms', 'водоем'),
    ('natural_waterbody_problem_terms', 'водохранилищ'),
    ('natural_waterbody_problem_terms', 'водоём'),
    ('natural_waterbody_problem_terms', 'возера'),
    ('natural_waterbody_problem_terms', 'высыхае'),
    ('natural_waterbody_problem_terms', 'высыхает'),
    ('natural_waterbody_problem_terms', 'обмел'),
    ('natural_waterbody_problem_terms', 'озеро'),
    ('natural_waterbody_problem_terms', 'рака'),
    ('natural_waterbody_problem_terms', 'река'),
    ('negative_condition_terms', 'аварийн'),
    ('negative_condition_terms', 'аварый'),
    ('negative_condition_terms', 'бракован'),
    ('negative_condition_terms', 'бруд'),
    ('negative_condition_terms', 'выгоняют'),
    ('negative_condition_terms', 'выселяют'),
    ('negative_condition_terms', 'высыхает'),
    ('negative_condition_terms', 'гряз'),
    ('negative_condition_terms', 'дефицит'),
    ('negative_condition_terms', 'дэфіцыт'),
    ('negative_condition_terms', 'заброшен'),
    ('negative_condition_terms', 'закрыли'),
    ('negative_condition_terms', 'закрылі'),
    ('negative_condition_terms', 'занядбан'),
    ('negative_condition_terms', 'запущен'),
    ('negative_condition_terms', 'затоп'),
    ('negative_condition_terms', 'испорчен'),
    ('negative_condition_terms', 'навязал'),
    ('negative_condition_terms', 'навязалі'),
    ('negative_condition_terms', 'навязан'),
    ('negative_condition_terms', 'небяспечна'),
    ('negative_condition_terms', 'невыплат'),
    ('negative_condition_terms', 'некачествен'),
    ('negative_condition_terms', 'неухожен'),
    ('negative_condition_terms', 'няма'),
    ('negative_condition_terms', 'няякасн'),
    ('negative_condition_terms', 'обмел'),
    ('negative_condition_terms', 'опасно'),
    ('negative_condition_terms', 'осыпается'),
    ('negative_condition_terms', 'отсутств'),
    ('negative_condition_terms', 'пагражае'),
    ('negative_condition_terms', 'перебо'),
    ('negative_condition_terms', 'подтоп'),
    ('negative_condition_terms', 'протеч'),
    ('negative_condition_terms', 'разбит'),
    ('negative_condition_terms', 'разбура'),
    ('negative_condition_terms', 'разбураецца'),
    ('negative_condition_terms', 'размыт'),
    ('negative_condition_terms', 'разрушается'),
    ('negative_condition_terms', 'сапсаван'),
    ('negative_condition_terms', 'списал'),
    ('negative_condition_terms', 'угрожает'),
    ('negative_condition_terms', 'чэрг'),
    ('negative_condition_terms', 'чэргі'),
    ('neutral_information_title_terms', 'инструкция'),
    ('neutral_information_title_terms', 'лайфхак'),
    ('neutral_information_title_terms', 'памятка'),
    ('neutral_information_title_terms', 'парады'),
    ('neutral_information_title_terms', 'разъяснили'),
    ('neutral_information_title_terms', 'рекомендации'),
    ('neutral_information_title_terms', 'рэкамендацыі'),
    ('neutral_information_title_terms', 'советы'),
    ('neutral_information_title_terms', 'інструкцыя'),
    ('official_response_terms', 'ліквідавалі'),
    ('official_response_terms', 'паабяцалі'),
    ('official_response_terms', 'пообещали'),
    ('official_response_terms', 'устранили'),
    ('persistence_terms', 'гадамі'),
    ('persistence_terms', 'годами'),
    ('persistence_terms', 'дагэтуль'),
    ('persistence_terms', 'месяцами'),
    ('persistence_terms', 'месяцамі'),
    ('persistence_terms', 'неаднаразова'),
    ('persistence_terms', 'неоднократно'),
    ('product_quality_context_terms', 'вытворц'),
    ('product_quality_context_terms', 'гаранти'),
    ('product_quality_context_terms', 'крама'),
    ('product_quality_context_terms', 'магазин'),
    ('product_quality_context_terms', 'пакупнік'),
    ('product_quality_context_terms', 'покупател'),
    ('product_quality_context_terms', 'продукт'),
    ('product_quality_context_terms', 'производител'),
    ('product_quality_context_terms', 'тавар'),
    ('product_quality_context_terms', 'товар'),
    ('product_quality_context_terms', 'упаковк'),
    ('profile_feature_exclusion_terms', 'знакомьтесь'),
    ('profile_feature_exclusion_terms', 'знаёмцеся'),
    ('provided_housing_problem_terms', 'грязь'),
    ('public_reaction_terms', 'абмеркаванне'),
    ('public_reaction_terms', 'абура'),
    ('public_reaction_terms', 'асцерагаюцца'),
    ('public_reaction_terms', 'возмущ'),
    ('public_reaction_terms', 'комментируют'),
    ('public_reaction_terms', 'недовольн'),
    ('public_reaction_terms', 'незадаволен'),
    ('public_reaction_terms', 'обеспокоен'),
    ('public_reaction_terms', 'обсуждают'),
    ('public_reaction_terms', 'обсуждение'),
    ('public_reaction_terms', 'опасаются'),
    ('public_reaction_terms', 'отклик'),
    ('public_reaction_terms', 'петици'),
    ('public_reaction_terms', 'поддержали'),
    ('public_reaction_terms', 'поддерживают'),
    ('public_reaction_terms', 'рассуждают'),
    ('resident_terms', 'бацьк'),
    ('resident_terms', 'граждан'),
    ('resident_terms', 'грамадзян'),
    ('resident_terms', 'дачник'),
    ('resident_terms', 'жител'),
    ('resident_terms', 'жыхар'),
    ('resident_terms', 'пакупнік'),
    ('resident_terms', 'пасажыр'),
    ('resident_terms', 'пассажир'),
    ('resident_terms', 'пациент'),
    ('resident_terms', 'пацыент'),
    ('resident_terms', 'покупател'),
    ('resident_terms', 'працаўнік'),
    ('resident_terms', 'работник'),
    ('resident_terms', 'родител'),
    ('shore_access_context_terms', 'бераг'),
    ('shore_access_context_terms', 'берег'),
    ('tourism_exclusion_terms', 'мотападарожж'),
    ('tourism_exclusion_terms', 'падарожж'),
    ('tourism_exclusion_terms', 'путешествен'),
    ('tourism_exclusion_terms', 'турагентств'),
    ('tourism_exclusion_terms', 'турист'),
    ('tourism_exclusion_terms', 'турыст'),
    ('urban_amenity_context_terms', 'алле'),
    ('urban_amenity_context_terms', 'бурьян'),
    ('urban_amenity_context_terms', 'кладбищ'),
    ('urban_amenity_context_terms', 'лавочк'),
    ('urban_amenity_context_terms', 'лесопарк'),
    ('urban_amenity_context_terms', 'мемарыял'),
    ('urban_amenity_context_terms', 'мемориал'),
    ('urban_amenity_context_terms', 'могілк'),
    ('urban_amenity_context_terms', 'набережн'),
    ('urban_amenity_context_terms', 'парк'),
    ('urban_amenity_context_terms', 'пустазелл'),
    ('urban_amenity_context_terms', 'скамейк'),
    ('urban_amenity_context_terms', 'сквер'),
    ('urban_amenity_context_terms', 'урн'),
    ('urban_greenery_context_terms', 'азелянен'),
    ('urban_greenery_context_terms', 'каштан'),
    ('urban_greenery_context_terms', 'магноли'),
    ('urban_greenery_context_terms', 'озеленен'),
    ('urban_greenery_context_terms', 'платан'),
    ('utility_water_context_terms', 'вадаправод'),
    ('utility_water_context_terms', 'водазабеспяч'),
    ('utility_water_context_terms', 'водопровод'),
    ('utility_water_context_terms', 'водоснабж'),
    ('utility_water_context_terms', 'жкх'),
    ('utility_water_context_terms', 'жэу'),
    ('utility_water_context_terms', 'квартир'),
    ('utility_water_context_terms', 'коммуналь'),
    ('utility_water_context_terms', 'подъезд'),
}


def test_no_new_unreviewed_bare_settings_terms():
    live = _scan_bare_short_terms()
    new = live - REVIEWED_BASELINE
    removed = REVIEWED_BASELINE - live
    assert not new, (
        f"New bare/short single-word entr(y/ies) added to a settings.yaml "
        f"*_terms list without lint review: {sorted(new)}. Either rephrase "
        f"as a multi-word phrase (the existing convention -- see 'дефицит "
        f"бюджета' instead of bare 'дефицит') or add to REVIEWED_BASELINE "
        f"in this file with a comment explaining why the bare form is safe."
    )
    assert not removed, (
        f"Entr(y/ies) removed/changed from the reviewed baseline: "
        f"{sorted(removed)}. If intentional, update REVIEWED_BASELINE to "
        f"match."
    )
